- name: webserver stop + remove
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Rocky > stop httpd
      service: name=httpd state=stopped
      when: ansible_distribution == 'Rocky'

    - name: Rocky > uninstall httpd
      action: "{{ ansible_pkg_mgr }} name=httpd state=absent"
      when: ansible_distribution == 'Rocky'

    - name: Ubuntu > stop nginx
      service: name=nginx state=stopped
      when: ansible_distribution == 'Ubuntu'

    - name: Ubuntu > uninstall nginx dependencies
      service: "{{ ansible_pkg_mgr }} name=nginx state=absent purge=true autoremove=yes"
      when: ansible_distribution == 'Ubuntu'
